server {
    server_name blog.iraamalia.id;

    root /var/www/blog;
    index index.html;

    access_log /var/log/nginx/blog.iraamalia.access.log;
    error_log  /var/log/nginx/blog.iraamalia.error.log;

    gzip on;
    gzip_types text/css application/javascript application/json application/xml application/rss+xml image/svg+xml;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;

    location ~* \.(css|js|svg|png|jpg|jpeg|webp|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/blog.iraamalia.id/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/blog.iraamalia.id/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = blog.iraamalia.id) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name blog.iraamalia.id;
    return 404; # managed by Certbot


}